[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:production"

[environment]
NODE_ENV = "production"

[[services]]
name = "zabbot-backend"
source = "./src/backend"

[services.variables]
PORT = "3001"